[package]
name = "metrical"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocksdb = "0.22.0"
serde = { version = "1.0.201", features = ["serde_derive", "derive"] }
serde_json = "1.0.117"
